Disable ansible-lint check

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,10 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-# if command -v cfn-lint > /dev/null
-# then
-#   npx lint-staged --quiet
-# else
-#   echo "ERROR: Please install cfn-lint"
-#   exit 1
-# fi
+if command -v cfn-lint > /dev/null
+then
+  npx lint-staged --quiet
+else
+  echo "ERROR: Please install cfn-lint"
+  exit 1
+fi
